### ISSUE TITLE
Empty branches dropdown button

### ISSUE THREAD

**Issue by markand** [boundstate/hgweb-boundstate-theme#11]
Hello,

Thanks for your beautiful theme!

I'm using it with Mercurial 3.5.1 and it works well, however I just wonder why my dropdown list does not show branches. I have an empty drop down menu.

See this capture:

![dd](https://cloud.githubusercontent.com/assets/11919008/11068619/7a736b6a-87d2-11e5-9823-cf93c53db052.png)

**Comment by mikejpeters** [comment]
I'm not sure how to reproduce this issue.  What browser are you using?

If you are brave please try downloading the [Beta release](https://github.com/boundstate/hgweb-boundstate-theme/releases/download/v2-beta/hgweb-boundstate-theme.zip) and see if you get the same issue.  I have it working with Mercurial 3.5.  It is a complete rewrite so you may run into some bugs but I will try to fix anything you run into, and I would prefer to support the new version instead of the old. Thanks!

**Comment by markand** [comment]
Seems to work better, however I'm unable to show files when clicking on them:

http://hg.malikania.fr/irccd/file

When you click on CMakeLists.txt, you get an empty file, it works with default Mercurial paper style though.

**Comment by mikejpeters** [comment]
Hey sorry for the delay on this.  I'm still not sure what's going on because even if I clone your repo on my machine I'm not getting the blank files.  I see that you've switched back to another theme.  It might help me if you can enable tracebacks (`import cgitb; cgitb.enable()`) in the `hgweb.cgi` file and see if it reports any kind of error when you try to view files with this theme.

**Comment by markand** [comment]
Hey,
I've finally found the problem, I really wonder how it worked for you, there was a missing '}' in branches.tmpl.

````
diff --git a/boundstate/branches.tmpl b/boundstate/branches.tmpl
index ecb3d91..a1bf80a 100644
--- a/boundstate/branches.tmpl
+++ b/boundstate/branches.tmpl
@@ -3,4 +3,4 @@
        <a href="{node|short}{sessionvars%urlparameter}" class="{status}">
                {branch|escape}
        </a>
-</li>'
+</li>'}
````

It just works now :)

**Comment by mikejpeters** [comment]
Thanks for finding that! 

Please open a separate issue if you are interested in using that beta version I linked to, but still have issues with viewing files. I'll try to investigate that when I get some free time.
